In [19]:
import librosa
import math
import matplotlib.pyplot as plt
import numpy as np

In [20]:
x = []
for i in range(20):    
    s, sr = librosa.load('x_ica_'+str(i+1)+'.wav', sr=None)
    x.append(s)

In [21]:
x = np.asmatrix(x)

In [22]:
x[:2,:2]


matrix([[ 0.00097656, -0.03457642],
        [ 0.00128174, -0.02944946]], dtype=float32)

In [23]:
cov_mat = np.cov(x)
eig_val, eig_vec = np.linalg.eig(cov_mat)

In [24]:
eig_val.shape

(20,)

In [25]:
eig_val

array([1.90443363e-01, 3.01367369e-02, 1.31554223e-02, 5.70160938e-03,
       7.57145485e-11, 7.59379785e-11, 7.93353721e-11, 7.63222590e-11,
       7.65418571e-11, 7.91242750e-11, 7.68671125e-11, 7.86620377e-11,
       7.85670584e-11, 7.84351361e-11, 7.83073562e-11, 7.80264623e-11,
       7.71022991e-11, 7.72917366e-11, 7.74497934e-11, 7.76385710e-11])

The eigen values from 5th one are all of the order e-11, so we consider first four eigen values/vectore

In [26]:
eig_vec_white = []
for i in range(4):
    eig_vec_white.append(eig_vec[i]/math.sqrt(eig_val[i]))
    #eig_vec[:,i] /= np.sqrt(eig_val[i])

In [27]:
Z = np.matmul(eig_vec_white, x)

In [28]:
Z[:4, :4]

matrix([[-6.49201465e-03,  1.51044133e-01,  4.75517810e-02,
          3.56846790e-01],
        [ 8.99606215e-03, -1.15291675e-01,  2.16100197e-01,
          1.81991451e-01],
        [-5.76683209e-02,  1.00146824e+00, -5.93983237e-01,
          7.28591184e-01],
        [ 3.01175525e-04,  3.22325160e-02,  1.17296680e-01,
          2.69193759e-01]])

In [29]:
x.shape

(20, 76800)

In [30]:
W = np.random.rand(4,4)
Y = np.matmul(W,Z)
L = 0.0000001

In [31]:
np.tanh(Y).shape

(4, 76800)

In [32]:
for i in range(1600):
    delta_W = np.matmul((x.shape[1]*np.identity(4) - np.matmul(np.tanh(Y) ,np.power(Y,3).T)),W)
    W = W + L*delta_W
    Y = np.matmul(W,Z)
    

In [33]:
Y = np.array(Y)

In [34]:
Y.shape

(4, 76800)

In [35]:
Y

array([[ 3.25869804e-02, -4.04944113e-01,  8.16536493e-01, ...,
        -4.71102266e-01, -4.38916171e-01, -5.46814328e-01],
       [-7.43867984e-04,  2.99275040e-02,  4.06032366e-02, ...,
         4.71747386e-01,  4.05818943e-01,  4.01706366e-01],
       [-8.22965562e-03,  2.75100822e-01,  3.09814968e-01, ...,
        -3.60109037e-01, -3.01723409e-01, -2.32752423e-01],
       [-9.32675798e-04,  1.80808315e-03, -4.78600403e-02, ...,
        -2.74662397e-01, -3.62182107e-01, -4.33703587e-01]])

In [36]:
for i in range(4):
    librosa.output.write_wav('x1_prob'+str(i+1)+'.wav',Y[i],  sr)